#!/bin/sh -e

case "$1" in
    remove)
        rm /usr/bin/postman
    ;;

	purge)
	;;

    disappear|upgrade|failed-upgrade|abort-install|abort-upgrade)
    ;;

    *) echo "$0: didn't understand being called with \`$1'" 1>&2
    ;;
esac

exit 0
